import React, { useMemo, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useKhata } from '@/context/KhataContext';
import { Card, Loading, SectionTitle, useKhataTheme } from '@/components/khata-ui';
import { TransactionSheet } from '@/components/TransactionSheet';
import { formatMoney, type MinorUnits } from '@/types';

export default function HomeScreen(){
 const {ready,accounts,transactions,categories,budgets,bills,settings}=useKhata(); const {palette,styles:ui}=useKhataTheme(); const [sheet,setSheet]=useState(false);
 const currency=settings?.defaultCurrency||'INR'; const now=new Date(); const start=new Date(now.getFullYear(),now.getMonth(),1).toISOString();
 const month=transactions.filter(t=>t.currency===currency&&t.date>=start); const income=month.filter(t=>t.type==='income').reduce((s,t)=>s+t.amount,0 as MinorUnits); const expenses=month.filter(t=>t.type==='expense').reduce((s,t)=>s+t.amount,0 as MinorUnits);
 const balance=accounts.filter(a=>a.currency===currency).reduce((s,a)=>s+a.currentBalance,0 as MinorUnits); const savings=income-expenses;
 const categoryTotals=useMemo(()=>{const map=new Map<string,number>();month.filter(t=>t.type==='expense').forEach(t=>map.set(t.categoryId||'other',(map.get(t.categoryId||'other')||0)+t.amount));return Array.from(map.entries()).sort((a,b)=>b[1]-a[1]).slice(0,4)},[month]);
 const recent=transactions.filter(t=>t.currency===currency).slice(0,4); if(!ready)return <Loading/>;
 return <View style={ui.screen}><ScrollView contentContainerStyle={ui.content} showsVerticalScrollIndicator={false}>
  <View style={s.top}><View><Text style={ui.eyebrow}>KHATA · TODAY</Text><Text style={[ui.title,{marginTop:4}]}>Good evening.</Text></View><View style={s.avatar}><Text style={s.avatarText}>T</Text></View></View>
  <Text style={ui.subtitle}>Everything about your money, kept private on this device.</Text>
  <Card style={s.balanceCard}><View style={ui.row}><View style={ui.grow}><Text style={s.cardLabel}>NET BALANCE</Text><Text style={[s.balance,{color:palette.text}]}>{formatMoney(balance,currency as any)}</Text></View><View style={s.private}><Text style={s.privateDot}>●</Text><Text style={s.privateText}>Offline</Text></View></View>
   <View style={s.statsRow}><MiniStat label="Income" value={formatMoney(income,currency as any)} color={palette.income}/><MiniStat label="Spent" value={formatMoney(expenses,currency as any)} color={palette.expense}/><MiniStat label="Saved" value={formatMoney(savings,currency as any)} color={palette.text}/></View>
  </Card>
  <View style={s.quickRow}><QuickAction label="Add money" symbol="↗" onPress={()=>setSheet(true)}/><QuickAction label="Record spend" symbol="↘" onPress={()=>setSheet(true)}/></View>
  <SectionTitle title="This month" action="Details"/><Card><View style={ui.row}><View style={ui.grow}><Text style={ui.small}>SAVINGS RATE</Text><Text style={[s.rate,{color:palette.text}]}>{income>0?Math.max(0,Math.round(savings/income*100)):0}%</Text></View><Text style={[s.status,{color:savings>=0?palette.income:palette.expense}]}>{savings>=0?'Healthy':'Above income'}</Text></View><View style={[ui.progressTrack,{marginTop:14}]}><View style={[ui.progressFill,{width:(income>0?Math.max(0,Math.min(100,savings/income*100)):0)+'%',backgroundColor:savings>=0?palette.income:palette.expense}]}/></View></Card>
  <SectionTitle title="Recent activity" action="See all"/><Card style={{paddingVertical:5}}>{recent.length===0?<Text style={ui.muted}>Your first transaction will appear here.</Text>:recent.map((t,i)=><View key={t.id} style={[ui.row,{paddingVertical:12},i<recent.length-1&&{borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:palette.border}]}><View style={[s.txIcon,{backgroundColor:t.type==='income'?palette.incomeSoft:palette.expenseSoft}]}><Text style={{fontSize:16,fontWeight:'900',color:t.type==='income'?palette.income:palette.expense}}>{t.type==='income'?'↑':'↓'}</Text></View><View style={ui.grow}><Text style={s.txName}>{categories.find(c=>c.id===t.categoryId)?.name||t.type}</Text><Text style={ui.small}>{t.note||accounts.find(a=>a.id===t.accountId)?.name||'Transaction'}</Text></View><Text style={[s.txAmount,{color:t.type==='income'?palette.income:palette.text}]}>{t.type==='income'?'+':'−'}{formatMoney(t.amount,currency as any)}</Text></View>)}</Card>
  <SectionTitle title="Where your money goes"/><Card>{categoryTotals.length===0?<Text style={ui.muted}>No spending recorded this month.</Text>:categoryTotals.map(([id,amount],i)=><View key={id} style={[ui.row,{paddingVertical:9}]}><View style={[s.categoryDot,{backgroundColor:[palette.accent,palette.warning,'#8B5CF6',palette.income][i]}]}/><Text style={[ui.grow,s.categoryName]}>{categories.find(c=>c.id===id)?.name||'Other'}</Text><Text style={ui.amount}>{formatMoney(amount as MinorUnits,currency as any)}</Text></View>)}</Card>
  {budgets[0]&&<><SectionTitle title="Budget"/><Card><View style={ui.row}><View style={ui.grow}><Text style={ui.small}>{budgets[0].name}</Text><Text style={[ui.amount,{marginTop:3}]}>{formatMoney(budgets[0].amount,currency as any)}</Text></View><Text style={ui.small}>monthly</Text></View></Card></>}
  {bills.filter(b=>!b.isPaid).slice(0,2).length>0&&<><SectionTitle title="Coming up"/><Card>{bills.filter(b=>!b.isPaid).slice(0,2).map(b=><View key={b.id} style={[ui.row,{paddingVertical:8}]}><View style={ui.grow}><Text style={s.txName}>{b.name}</Text><Text style={ui.small}>Due {new Date(b.dueDate).toLocaleDateString()}</Text></View><Text style={ui.amount}>{formatMoney(b.amount,currency as any)}</Text></View>)}</Card></>}
 </ScrollView><Pressable style={ui.fab} onPress={()=>setSheet(true)}><Text style={ui.fabText}>+</Text></Pressable><TransactionSheet visible={sheet} onClose={()=>setSheet(false)}/></View>;
}
function MiniStat({label,value,color}:{label:string;value:string;color:string}){return <View style={{flex:1}}><Text style={s.statLabel}>{label}</Text><Text style={[s.statValue,{color}]}>{value}</Text></View>}
function QuickAction({label,symbol,onPress}:{label:string;symbol:string;onPress:()=>void}){const {palette}=useKhataTheme();return <Pressable onPress={onPress} style={({pressed})=>[s.quick,{backgroundColor:palette.surface,borderColor:palette.border},pressed&&{opacity:.65}]}><View style={s.quickIcon}><Text style={s.quickSymbol}>{symbol}</Text></View><Text style={s.quickLabel}>{label}</Text></Pressable>}
const s=StyleSheet.create({top:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},avatar:{width:40,height:40,borderRadius:20,backgroundColor:'#171717',alignItems:'center',justifyContent:'center'},avatarText:{color:'#fff',fontWeight:'800'},balanceCard:{marginTop:20,padding:18},cardLabel:{fontSize:11,fontWeight:'900',letterSpacing:1,color:'#777770'},balance:{fontSize:36,fontWeight:'800',letterSpacing:-1.4,marginTop:4},private:{flexDirection:'row',alignItems:'center',gap:5,backgroundColor:'#F0F6F1',paddingHorizontal:9,paddingVertical:6,borderRadius:999},privateDot:{fontSize:9,color:'#17834B'},privateText:{fontSize:11,fontWeight:'800',color:'#17834B'},statsRow:{flexDirection:'row',gap:8,marginTop:22,paddingTop:16,borderTopWidth:StyleSheet.hairlineWidth,borderTopColor:'#E5E5DF'},statLabel:{fontSize:11,color:'#777770',fontWeight:'700'},statValue:{fontSize:14,fontWeight:'800',marginTop:4},quickRow:{flexDirection:'row',gap:10,marginTop:12},quick:{flex:1,minHeight:62,borderRadius:17,borderWidth:1,flexDirection:'row',alignItems:'center',paddingHorizontal:12,gap:10},quickIcon:{width:34,height:34,borderRadius:12,backgroundColor:'#EEF1FF',alignItems:'center',justifyContent:'center'},quickSymbol:{fontSize:17,fontWeight:'900',color:'#315CFF'},quickLabel:{fontSize:13,fontWeight:'800',color:'#171717'},rate:{fontSize:25,fontWeight:'800',marginTop:3},status:{fontSize:12,fontWeight:'800'},txIcon:{width:38,height:38,borderRadius:13,alignItems:'center',justifyContent:'center',marginRight:11},txName:{fontSize:14,fontWeight:'800',color:'#171717'},txAmount:{fontSize:14,fontWeight:'800'},categoryDot:{width:9,height:9,borderRadius:5,marginRight:10},categoryName:{fontSize:14,fontWeight:'700',color:'#292927'}});
