import React, { useMemo, useState } from 'react';
import { Alert, FlatList, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { useKhata } from '@/context/KhataContext';
import { Card, Loading, useKhataTheme } from '@/components/khata-ui';
import { TransactionSheet } from '@/components/TransactionSheet';
import { formatMoney } from '@/types';

type Filter='all'|'income'|'expense';
export default function TransactionsScreen(){
 const {ready,transactions,categories,accounts,settings,removeTransaction}=useKhata(); const {palette,styles:ui}=useKhataTheme();
 const [query,setQuery]=useState(''),[filter,setFilter]=useState<Filter>('all'),[sheet,setSheet]=useState(false); const currency=settings?.defaultCurrency||'INR';
 const filtered=useMemo(()=>transactions.filter(t=>{if(t.currency!==currency||(filter!=='all'&&t.type!==filter))return false;const hay=[t.note||'',categories.find(c=>c.id===t.categoryId)?.name||'',accounts.find(a=>a.id===t.accountId)?.name||''].join(' ').toLowerCase();return hay.includes(query.trim().toLowerCase())}),[transactions,categories,accounts,query,currency,filter]);
 const groups=useMemo(()=>{const map=new Map<string,typeof filtered>();filtered.forEach(t=>{const key=new Date(t.date).toLocaleDateString(undefined,{month:'long',year:'numeric'});if(!map.has(key))map.set(key,[]);map.get(key)!.push(t)});return Array.from(map.entries())},[filtered]);
 if(!ready)return <Loading/>;
 return <View style={ui.screen}><FlatList data={groups} keyExtractor={([month])=>month} contentContainerStyle={[ui.content,{paddingBottom:140}]} showsVerticalScrollIndicator={false}
  ListHeaderComponent={<View><View style={s.header}><View><Text style={ui.eyebrow}>LEDGER</Text><Text style={[ui.title,{marginTop:4}]}>Activity</Text></View><View style={s.filterButton}><Text style={s.filterIcon}>≡</Text></View></View>
   <View style={[s.search,{backgroundColor:palette.surface,borderColor:palette.border}]}><Text style={s.searchIcon}>⌕</Text><TextInput value={query} onChangeText={setQuery} placeholder="Search transactions" placeholderTextColor="#92928B" style={s.input}/>{query.length>0&&<Pressable onPress={()=>setQuery('')}><Text style={s.clear}>×</Text></Pressable>}</View>
   <View style={s.chips}>{(['all','expense','income'] as Filter[]).map(x=><Pressable key={x} onPress={()=>setFilter(x)} style={[s.chip,{backgroundColor:filter===x?palette.primary:palette.surface,borderColor:filter===x?palette.primary:palette.border}]}><Text style={[s.chipText,{color:filter===x?palette.primaryText:palette.muted}]}>{x==='all'?'All':x==='expense'?'Spent':'Income'}</Text></Pressable>)}</View>
   <View style={s.summary}><Text style={ui.small}>{filtered.length} {filtered.length===1?'transaction':'transactions'}</Text><Text style={[s.summaryText,{color:palette.text}]}>Local only · no sync</Text></View>
  </View>}
  renderItem={({item:[month,items]})=><View><Text style={s.month}>{month}</Text><Card style={{paddingVertical:4}}>{items.map((t,i)=><Pressable key={t.id} onLongPress={()=>Alert.alert('Delete transaction?','This entry will be removed from your local ledger.',[{text:'Cancel',style:'cancel'},{text:'Delete',style:'destructive',onPress:()=>removeTransaction(t.id)}])} style={[s.tx,i<items.length-1&&{borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:palette.border}]}><View style={[s.icon,{backgroundColor:t.type==='income'?palette.incomeSoft:palette.expenseSoft}]}><Text style={{fontSize:16,fontWeight:'900',color:t.type==='income'?palette.income:palette.expense}}>{t.type==='income'?'↑':'↓'}</Text></View><View style={ui.grow}><Text style={s.name}>{categories.find(c=>c.id===t.categoryId)?.name||t.type}</Text><Text style={ui.small}>{t.note||accounts.find(a=>a.id===t.accountId)?.name||'Transaction'}</Text><Text style={s.date}>{new Date(t.date).toLocaleDateString(undefined,{day:'numeric',month:'short'})}</Text></View><Text style={[s.amount,{color:t.type==='income'?palette.income:palette.text}]}>{t.type==='income'?'+':'−'}{formatMoney(t.amount,currency as any)}</Text></Pressable>)}</Card></View>}
  ListEmptyComponent={<Card style={{marginTop:18,alignItems:'center',paddingVertical:32}}><View style={s.emptyIcon}><Text style={s.emptySymbol}>⌕</Text></View><Text style={s.emptyTitle}>{query?'Nothing found':'No transactions yet'}</Text><Text style={[ui.muted,{textAlign:'center',marginTop:5}]}>{query?'Try a different note, account or category.':'Add your first transaction and Khata will build your private ledger.'}</Text></Card>}
 /><Pressable style={ui.fab} onPress={()=>setSheet(true)}><Text style={ui.fabText}>+</Text></Pressable><TransactionSheet visible={sheet} onClose={()=>setSheet(false)}/></View>;
}
const s=StyleSheet.create({header:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},filterButton:{width:42,height:42,borderRadius:14,backgroundColor:'#fff',borderWidth:1,borderColor:'#E5E5DF',alignItems:'center',justifyContent:'center'},filterIcon:{fontSize:22,color:'#171717'},search:{height:52,borderRadius:16,borderWidth:1,marginTop:16,flexDirection:'row',alignItems:'center',paddingHorizontal:13},searchIcon:{fontSize:25,color:'#777770',marginRight:8,marginTop:-2},input:{flex:1,fontSize:15,color:'#171717',height:50},clear:{fontSize:24,color:'#777770',paddingHorizontal:4},chips:{flexDirection:'row',gap:8,marginTop:10},chip:{paddingHorizontal:15,paddingVertical:9,borderRadius:999,borderWidth:1},chipText:{fontSize:12,fontWeight:'800'},summary:{flexDirection:'row',justifyContent:'space-between',marginTop:16},summaryText:{fontSize:12,fontWeight:'700'},month:{fontSize:13,fontWeight:'900',color:'#777770',marginTop:24,marginBottom:9},tx:{minHeight:70,flexDirection:'row',alignItems:'center',paddingVertical:11},icon:{width:40,height:40,borderRadius:13,alignItems:'center',justifyContent:'center',marginRight:11},name:{fontSize:14,fontWeight:'800',color:'#171717'},date:{fontSize:11,color:'#999991',marginTop:2},amount:{fontSize:14,fontWeight:'900',marginLeft:10},emptyIcon:{width:52,height:52,borderRadius:18,backgroundColor:'#F0F0EC',alignItems:'center',justifyContent:'center'},emptySymbol:{fontSize:25,color:'#777770'},emptyTitle:{fontSize:16,fontWeight:'900',color:'#171717',marginTop:12}});
