import React, { useMemo, useState } from 'react';
import { Modal, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useKhata } from '@/context/KhataContext';
import { Button, Field, palette, styles as ui } from './khata-ui';
import { toMinorUnits, type EntityId, type TransactionType } from '@/types';

export function TransactionSheet({visible,onClose}:{visible:boolean;onClose:()=>void}) {
  const {accounts,categories,addTransaction,addTransfer,settings}=useKhata();
  const [type,setType]=useState<TransactionType>('expense'),[amount,setAmount]=useState(''),[accountId,setAccountId]=useState<EntityId|''>(''),[toAccountId,setToAccountId]=useState<EntityId|''>(''),[categoryId,setCategoryId]=useState<EntityId|''>(''),[note,setNote]=useState(''),[saving,setSaving]=useState(false);
  const cats=useMemo(()=>categories.filter(c=>!c.parentId&&(c.type===type||c.type==='both')),[categories,type]);
  const reset=()=>{setAmount('');setAccountId('');setToAccountId('');setCategoryId('');setNote('');setType('expense');};
  const submit=async()=>{const value=Number(amount);if(!value||value<=0||!accountId)return;setSaving(true);try{const currency=settings?.defaultCurrency||'INR';if(type==='transfer'){if(!toAccountId||toAccountId===accountId)return;await addTransfer({amount:toMinorUnits(value,currency as any),currency,fromAccountId:accountId as EntityId,toAccountId:toAccountId as EntityId,note:note.trim()||undefined,date:new Date().toISOString()});}else{await addTransaction({type,amount:toMinorUnits(value,currency as any),currency,accountId:accountId as EntityId,categoryId:categoryId||undefined,note:note.trim()||undefined,date:new Date().toISOString()});}reset();onClose();}finally{setSaving(false);}};
  return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><View style={s.backdrop}><View style={s.sheet}><View style={s.handle}/><ScrollView contentContainerStyle={s.content}><View style={ui.row}><View style={ui.grow}><Text style={ui.title}>Add transaction</Text><Text style={ui.subtitle}>Timestamp is captured automatically.</Text></View><Pressable onPress={onClose}><Text style={{fontSize:24,color:palette.muted}}>×</Text></Pressable></View>
    <View style={s.segment}>{(['expense','income','transfer'] as TransactionType[]).map(x=><Pressable key={x} onPress={()=>setType(x)} style={[s.segmentItem,type===x&&s.selected]}><Text style={[s.segmentText,type===x&&s.selectedText]}>{x[0].toUpperCase()+x.slice(1)}</Text></Pressable>)}</View>
    <Field label="Amount" keyboardType="decimal-pad" placeholder="0" value={amount} onChangeText={setAmount} autoFocus/>
    <Text style={ui.label}>Account</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.chips}>{accounts.map(a=><Pressable key={a.id} onPress={()=>setAccountId(a.id)} style={[s.chip,accountId===a.id&&s.chipSelected]}><Text style={[s.chipText,accountId===a.id&&s.chipTextSelected]}>{a.name}</Text></Pressable>)}</ScrollView>
    {type==='transfer'?<><Text style={ui.label}>Move to</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.chips}>{accounts.filter(a=>a.id!==accountId).map(a=><Pressable key={a.id} onPress={()=>setToAccountId(a.id)} style={[s.chip,toAccountId===a.id&&s.chipSelected]}><Text style={[s.chipText,toAccountId===a.id&&s.chipTextSelected]}>{a.name}</Text></Pressable>)}</ScrollView></>:<><Text style={ui.label}>Category</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.chips}>{cats.map(c=><Pressable key={c.id} onPress={()=>setCategoryId(c.id)} style={[s.chip,categoryId===c.id&&s.chipSelected]}><Text style={[s.chipText,categoryId===c.id&&s.chipTextSelected]}>{c.name}</Text></Pressable>)}</ScrollView></>}
    <Field label="Note (optional)" placeholder="Dinner, salary, fuel…" value={note} onChangeText={setNote}/><Button title={saving?'Saving…':'Save transaction'} onPress={submit} disabled={saving||!amount||!accountId||(type==='transfer'&&!toAccountId)}/>
  </ScrollView></View></View></Modal>;
}
const s=StyleSheet.create({backdrop:{flex:1,backgroundColor:'rgba(0,0,0,.38)',justifyContent:'flex-end'},sheet:{maxHeight:'92%',backgroundColor:'#FFF',borderTopLeftRadius:28,borderTopRightRadius:28},handle:{width:42,height:5,borderRadius:3,backgroundColor:'#D4D4D8',alignSelf:'center',marginTop:9},content:{padding:20,paddingBottom:36},segment:{flexDirection:'row',backgroundColor:'#F0F0F3',padding:4,borderRadius:14,marginVertical:18},segmentItem:{flex:1,paddingVertical:11,alignItems:'center',borderRadius:11},selected:{backgroundColor:'#FFF',shadowColor:'#000',shadowOpacity:.08,shadowRadius:5,elevation:2},segmentText:{fontSize:13,fontWeight:'600',color:palette.muted},selectedText:{color:palette.text},chips:{gap:8,paddingVertical:9},chip:{paddingHorizontal:13,paddingVertical:10,borderRadius:14,backgroundColor:'#F4F4F6',borderWidth:1,borderColor:'#F4F4F6'},chipSelected:{backgroundColor:'#111113',borderColor:'#111113'},chipText:{fontSize:13,color:palette.muted,fontWeight:'600'},chipTextSelected:{color:'#FFF'}});
